language: node_js
node_js:
- '7'
script: printf "\nREM OFFICIAL - HOST DEPLOYMENT"
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: fBFkgUnme2is4XDS5ToeFFY4VbyGOOrDx/jnpWNWYjeyoNLDMi8A4Icdfnhi+Ir2H8fwwSDBl+oavPes1Vl5WcQUCCb+YzANdfygQjC+nUBIoCEx1Hjl3Jsex1CUOKPlNNGcI5W+HkN9yEr/pLLnTHXzJmsLnpExUq6P8v9Jcb8n8hPSeVMNkGW5efQuQ1A3sOEiffA6T7MSzmIyillUx9jHdw/CQlsZisrlt9cfgVnBATBLa5Knxc88KSq8Yh4t8PNyMJRU3IR4L6aIw0UGKe9SOlkucTreD5IBDdLoTEqVQCMGGAo/pgNa2bRF/hEh2Mo38GnaUlXaJonBxrbH0rmLY3P1a5yFfpuzhmaG5BS+anZ/dBWxlyDgbTUo2oHnJlDKJTso7UvxZhLT/RAH7MDnX873V/VHssiqfDrMaJAD8bq54gFypjCPJdMvozceFU3fp6fD66vIgi/6smtufHLJDfLy4c8XAlze9nwpCNy9Z+A2U1hAOWED51F7TH8Ig/2jxQAz+LzyAFT2dWMWGu5AnQD7Z36xp6CycLuNo590zt6BQHNnRTpOxxTepb7HED41dHDyKrWt0h35IN3wuqbeewew6jEEuwRYqOUsHJyRTmL/QpTRokGNPO1j6bekzV5fvTsIBdyvcRrTZrWA/lyGw8yVb8+v7hdI/gFf3ak=
  message: via Travis CI
after_deploy:
- wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
- chmod +x send.sh
- "./send.sh success $WEBHOOK_URL"
after_failure:
- wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
- chmod +x send.sh
- "./send.sh failure $WEBHOOK_URL"
