language: node_js
node_js:
- '7'
script: printf "\nREM OFFICIAL - HOST DEPLOYMENT"
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: S4VD5VHB3ht0LNJE3UCnnanMzlSajiNsbkeKFyZD1Fd5dPJNe0w0o/YYyrLVs3f1c+vhAtt1lJu4VKp6hlmn3hzFXkx924idM9tL35qsVJItBB0ArLsgT6xZ2XTJRsftr5vBtz7N7nCr2zB/D4im3oPtxXIjBAAVxORn4G1/L7/AirGX+8AgIRn9dwAcmDtx92tmC6xldNcmQDAPI0uKtsVl4vnM5WvbX9Ha6Cz5YJ+3VI8CEXZbuAI88Fu78e/6SeMZEG5DGy3rpKTmeanlfveumC179MzWpjDjlrcobaKBTagHiGnbJUK8hxzgPkZ3bQJUHP4N09J6EdX+sAjTIcvP6IVbp3xowbe9SMqhL1yyCmKTUOLA6H1wFsZh6Z4ciaBcGYx+QHj1TomVjGYLu4vSozIZHmPDEx2aCioIEXOlev8vz3vTYYOIkEuwCCaPyY+lSunmIwDz4EhkNktvOPcZ9QB/YY/O83TnaeAqitKKTFDnnlL6Yf4yVB5BNmyD8tArpc/Vjp80YkqErDB7ZoGx9n2qCejSulS8hSahs14pAYumyKxPTRpadHdJtvISljG9MBpWNhHqH/wPoJvMrzjPyJ/oSAx46R+4rqYIgvMDEUlwrxgormovoTYyH8zlItJcQhdgs5IfKM6IV4XwNblMGmSVPauwARhpprdHbGs=
  message: via Travis CI
after_deploy:
- wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
- chmod +x send.sh
- "./send.sh success $WEBHOOK_URL"
after_failure:
- wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
- chmod +x send.sh
- "./send.sh failure $WEBHOOK_URL"
