language: node_js
node_js:
- '7'
script: printf "\nREM OFFICIAL - HOST DEPLOYMENT"
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: TEw/bcv56tX9cS4LiEsPHUoomq8u28LsAzvHwV0w/2iA7pheWS4KRmim/v/ToUKypkLbw6Qm6UE0TG3PWlFSbr1tHECMOCV3/WlHgZ3TtYAECdbX0VqU5gUwTljCUao/Ef1EebNZciNxIaB6zGD5vS9n/rJMKd3TEksUwegWUG6AbGJb4qfI1t0mJ+IQgtMavbKpNuz7lW+7aC0BDsv6Y3FbXzF+4QAwTbLnrea2ldCy6Jr4vseJotcLWbdCziz/9n2X+PnDFWF4oZzvFtKSy/JB9stegW9FeQUvWNKsDtpquGDhdehPzGl9Wx1/Txd/VrVH0Alr3rSA3f98DstjpB7Y74Aoz2DXN4qjkZjBM3gp5Co4JhancC3w2FSOQEPdGJGYQhDyZO0isoxSEdwcTj5N4pt3AVN6Q7jvK8wxgTJP49TAMwKvZvV6mHu/4gYrR6vKuRUPwOj7SXjV3+1GEXLMJ95aVXSOybcBOrHGGvubhjcIXDqpyRdBXcfPTuJF1qDs5YUsvC1wvstzTHhMv00WP8r/8BqHzutAMT/LQ8tPmmjmuo6ci4Zrd9ejsqLR/QzDJyfS01oNh4CHIgfsd9wk/dc3mWIrWHC96LdIRlQyuSTy64DMtBqpU6D73XNepEVUi91Jm+2P4hGgO3BsEPYeR+j/F/bqDnUAR4XRp0M=
  message: via Travis CI
after_deploy:
- wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
- chmod +x send.sh
- "./send.sh success $WEBHOOK_URL"
after_failure:
- wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
- chmod +x send.sh
- "./send.sh failure $WEBHOOK_URL"
