language: node_js
node_js:
 — “7”
script:
 — echo “REM OFFICIAL - HOST DEPLOYMENT”
install:
 — npm install -g firebase-tools
after_success:
 — firebase deploy — project rem-official — token $FIREBASE_TOKEN.