language: node_js
node_js:
- '7'
script: printf "\nREM OFFICIAL - HOST DEPLOYMENT"
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: RJcnPOiC/cFaq8fnmTatU6mwAmdQfh8ZB+t6QQlWYuuuD47WJkcAkRgHkn9ZC2dtRMHoAgLZERb0xWiSGJsQjf2cojTl/AE8IvOPP7RBvVTWHXtSMNS4pGnQzWciQPP4t6KKksjQ3g33h4edUS3ruJlWSP6YX2z73/R69WEasHW/XW6QaFOCIuYUhXL0/OgADjfHj4RNgnQo+ULVQLMDHX5m16tR190XfxiDnNL6CwG3yT4bBIwh/W7ZicjC07o8YTkg4O/loAzroFe9LlKPB+5HRBc3c0pIl1KtGX7VPDQrSV9I0F0jjvCfBqHI4qcOoXbUPRid/17tFbyJgBCBzHzu1SjvO32HtC+s785NwQyN8Mk0nlLb+8DosfcroawfiQaPlapg9T8FE8nqbgssQxqBbxB/qtyS7A55dV/rPTOS42UNRsfx3s0NHCij6m7lp11GTgafV76uaMfJeFxFnzmVIQC4r8kaKHljckXycq3zi2kT6dDtuYNJSGldJpGQxRqIN0WLEfePG8AD1uPLnJwyCINs7njWMroT81FdkUfHqDiI36h4ASzy8O4siM7HRBK5jNov5ceNlEXa8S+SxyiAFgE5IojaMTZyEfSpKxNdzwUZtZ78OSYyxRDZchCE5UqnKkb8deRpA+dgEC7WTgw+fVcV+KtkUMtaZYOD3/Y=
  message: via Travis CI
after_deploy:
- wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
- chmod +x send.sh
- "./send.sh success $WEBHOOK_URL"
after_failure:
- wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
- chmod +x send.sh
- "./send.sh failure $WEBHOOK_URL"
